services:
  rpi-monitor:
    container_name: rpi-monitor
    image: thiagomag/rpi-monitor
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000:5000
    networks:
      - rpi-network
    restart: unless-stopped

networks:
  rpi-network:
    external: true